version: "3.9"

services:
  api:
    env_file:
      - .env
    container_name: ${APP_NAME}
    hostname: ${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    volumes:
      - ./data:/data

    ports:
      - ${PORT}:${PORT}

    restart: always
